[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
basket = "gnnZfKE3rrrK6HFhSrmRafN1LfWUdfyRp7cBzNyPAdP"

[programs.mainnet]
basket = "9LNEoShrH93XekWQTFmZBdUdMu8ugJxBr5cbfqJQC1mw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "deployer-keypair.json"

[workspace]
members = ["programs/basket"]

[scripts]
build-mainnet = "anchor build"
deploy-mainnet = "anchor deploy --provider.cluster mainnet"
test = "cargo test -p basket"
