[package]
name = "omnindex"
version = "0.1.0"
description = "Fixed-ratio basket index protocol on Solana"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "lib"]
name = "omnindex"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", default-features = false, features = ["token", "token_2022"] }
mpl-token-metadata = "5.1.1"
switchboard-on-demand = { version = "0.12.1", default-features = false, features = ["anchor"] }
